#!/bin/bash
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="zcash"

ARCH="$(uname -m)"
BUILD_DIR="$(mktemp -d)"

cp Dockerfile.${ARCH} "$BUILD_DIR/Dockerfile"
[[ $ARCH = "x86_64" ]] || {
  DOCKER_IMAGE="$ARCH-$DOCKER_IMAGE"
}

TAG="$DOCKER_USER/$DOCKER_IMAGE"

echo "Building $TAG in $BUILD_DIR"
docker build -t $TAG "$BUILD_DIR/"
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG
